name: Deploy Glimpse API to cPanel Subdomain

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan tombol manual "Run workflow" di GitHub Actions

jobs:
  web-deploy:
    name: Deploy Laravel API via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, json, pdo, sqlite, pdo_sqlite

    - name: Copy .env.example if .env not present
      run: cp .env.example .env

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

    - name: Sync Files via LFTP (Resilient Plain FTP)
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -e "set ftp:ssl-allow no; set ftp:passive-mode yes; mirror -R --ignore-time --parallel=10 --exclude-glob .git* --exclude-glob node_modules* --exclude-glob tests* --exclude-glob vendor* --exclude-glob storage/framework/cache/data* --exclude-glob storage/framework/sessions* --exclude-glob storage/framework/views* --exclude-glob storage/logs* ./ ./; quit" -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}"
